@startuml
skinparam monochrome true
actor ThirdParty as TP
participant Sender as SND
participant RequestManager as REQ
participant AuthenticationService as AUTH
participant DataBase as DB
participant AnonymizationService as NOT

TP -> REQ : askGroupData(ReqParams, filters, token, callback, isSub)
activate REQ
REQ -> AUTH: authRequest(token)
activate AUTH
AUTH --> REQ: VAT_Code
deactivate AUTH


REQ -> DB : addReqToDB(params, filters, callback, vat, isSub, initState)
activate DB
DB -> DB: check if it is aready existing
activate DB
deactivate DB
DB --> REQ : reqID
deactivate DB

REQ --> TP : reqID
REQ -> NOT : checkAnonym(req_ID)
activate NOT
NOT -> DB : query
activate DB
DB --> NOT : numberOfUsers
deactivate DB

alt
NOT -> REQ : ok
REQ -> SND : send(req_ID)
deactivate REQ
activate SND
SND -> SND : builds message using filters and parameters
activate SND
deactivate SND
SND -> TP: Data
deactivate SND

else

NOT -> REQ : nok
activate REQ
REQ -> SND : send(error)
deactivate REQ
activate SND
SND -> TP: Error
deactivate SND

end
@enduml