@startuml
skinparam monochrome true
actor ThirdParty as TP
participant Sender as SND
participant RequestManager as REQ
participant AuthenticationService as AUTH
participant AnonymizationService as NOT

TP -> REQ : askGroupData(ReqParams, filters, token, callback, isSub)
activate REQ
REQ -> AUTH: authRequest(token)
activate AUTH
AUTH --> REQ: VAT_Code
deactivate AUTH


REQ -> REQ : addGroupReq(params, filters, callback, VAT_Code)
activate REQ
deactivate REQ

REQ -> NOT : isAnonymizable(req_ID)
activate NOT

alt anonymizable group
NOT --> REQ : YES

REQ -> SND : send(req_ID)
deactivate REQ
activate SND
SND -> SND : builds message using filters and parameters
activate SND
deactivate SND
SND -> TP: GroupData
deactivate SND

else not enough users

NOT -> REQ : NO
deactivate NOT

activate REQ
REQ -> SND : send(error)
deactivate REQ
activate SND
SND -> TP: Error
deactivate SND

end
@enduml