@startuml
skinparam monochrome true

actor ThirdParty as TP
participant Sender as SND
participant RequestManager as REQ
participant AuthenticationService as AUTH
participant UserNotificationService as NOT
actor User

TP -> REQ : askUserData(ReqParams, UserID, token, callback, isSub)
activate REQ
REQ -> AUTH: authRequest(token)
activate AUTH
AUTH --> REQ: VAT
deactivate AUTH
REQ -> REQ : addSingleReq(params, callback, VAT)
activate REQ
deactivate REQ
REQ -> NOT : sendPermissionRequest(VAT_Code, userID)
activate NOT
REQ --> TP : req_ID
deactivate REQ
NOT -> User : send mail
deactivate NOT
activate User

... ...

User -> NOT : grant permission
deactivate User
activate NOT

NOT -> NOT : modifyRequest(req_ID)
activate NOT
deactivate NOT

NOT -> REQ : notifyUserResponse(UserID, ReqID, response)
deactivate NOT
activate REQ

REQ -> SND : send(req_ID)
deactivate REQ
activate SND
SND -> SND : builds message using filters and parameters
activate SND
deactivate SND
SND -> TP: UserData
deactivate SND
@enduml