@startuml
skinparam monochrome true
actor DataSource as DS
participant Receiver as RCV
participant AuthenticationService as AUTH
participant SubscriptionService as SUB
participant AnonymizationService as ANON
participant Sender as SND
actor ThirdParty as TP

DS -> RCV  : sendData(token, paramType, value)
activate RCV
RCV -> AUTH : auth(token)
activate AUTH
AUTH --> RCV : return DS_ID
deactivate AUTH
RCV -> RCV : saveData(DS_ID, paramType, value)
activate RCV
deactivate RCV
RCV -> SUB: notify(userID, paramType)
deactivate RCV
activate SUB

SUB -> SUB: checkSingleSubscriptions(userID)
activate SUB
deactivate SUB

loop for each single user subscription
SUB -> SND: send(req_id)
activate SND
SND -> SND : buildResponse (req_id)
activate SND
deactivate SND
SND ->TP : sendResponse(response)
deactivate SND
end loop

SUB -> SUB: checkGroups(userID, paramType)
activate SUB
deactivate SUB

loop for each group data subscription
SUB -> ANON : checkAnon(req_id)
activate ANON
ANON --> SUB : OK
deactivate ANON
SUB -> SND: send(req_id)
deactivate SUB
activate SND
SND -> SND : buildResponse (req_id)
activate SND
deactivate SND
SND ->TP : sendResponse(response)
deactivate SND
end loop
@enduml