@startuml

autonumber "<b>[0]:</b>"
skinparam monochrome  true

actor User
participant App<<AutomatedSOS>>
participant MonitoringService<<AutomatedSOS>>
participant Data4Help
activate User

create App
activate App
User -> App : <<download>>

App -> User : askDeviceAccessPermissions()
activate User #lightgrey
User -->> App : grantPermissions()
deactivate User

App -> User : askCredentials()
activate User #lightgrey
User -->> App : provideCredentials(D4H_credentials)
deactivate User 


App -> MonitoringService : addUser(D4H_credentials)
activate MonitoringService
MonitoringService -> MonitoringService: addUserToSystem()
activate MonitoringService  #lightgrey
deactivate MonitoringService


group Subscribe to User Data 
	MonitoringService -> Data4Help : getAccessToken(D4H_credentials)
	activate Data4Help
	
alt Authenication OK	
	Data4Help -->> MonitoringService : grantAccessToken(token)
	deactivate Data4Help
	MonitoringService -> Data4Help : requestDataSubscription(token, user_id, callback)
	activate Data4Help
	Data4Help -> Data4Help : authenticateRequest(token)
	activate Data4Help #lightgrey
	deactivate Data4Help 
	Data4Help -> User : askPermission()
	activate User #lightgrey
	User -->> Data4Help : grantPermission()
	deactivate User
	Data4Help -> Data4Help : addToListeners(user_id, callback)
	activate Data4Help #lightgrey 
	deactivate Data4Help
	Data4Help -->> MonitoringService : confirmSubscription()
	
	MonitoringService -->> App : confirmUser()
	
	App -> User : confirmActivation()
	
else Authentication Error
	autonumber 9
	Data4Help -->> MonitoringService : denyAccess()
	deactivate Data4Help

	MonitoringService -->> App : notifyError(synch_error)
	deactivate MonitoringService
	
	App -->> User : notify_error(synch_error)
	deactivate App
	deactivate User
end
end

deactivate App
deactivate User
@enduml